### ISSUE TITLE
Update for Carthage Preview 1

### ISSUE THREAD

**Issue by WildWeazel** [C7-Game/c7-game.github.io#1]
Update release notes and download links for Carthage

**Comment by QuintillusCFC** [comment]
Looks like you did this on July 10th.  And this was the one step I forgot in the Preview 2 release, despite having written the how-to on releases.  It's now pointing to Preview 2.

See also my [recent CFC post](https://forums.civfanatics.com/threads/poll-c7-system-requirements.675976/#post-16308175), where I note that Babylon got a lot more downloads than Carthage Preview 1.  This suggests that a lot of people used the links on c7-game.github.io, although it could just be that not many people were interested in Carthage Preview 1.  Still, it suggests that it's probably important to update those links, and thus find a way to make it less easy to forget to update them.

I've bolded that step in the release notes.  But maybe we should try to automate it?

**Comment by QuintillusCFC** [comment]
(Closing the current issue, we can keep discussing it though)

**Comment by WildWeazel** [comment]
I'm in favor of automating whatever can be automated within reason. If we can embed the latest release on the page that should be sufficient.
edit: I'm not seeing any way to embed the card but here's some info on using the API to script something: https://gist.github.com/dleidert/99a8e6ee3a879a7ed1f160c5dd07c13d
